version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      wasmtime-deps:
        patterns:
          - "wasmtime*"
          - "wasi-common"
        update-types:
          - "patch"
      patch:
        update-types:
          - "patch"
    ignore:
      - dependency-name: "wasmtime*"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
      - dependency-name: "wasi-common"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
