version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "wasmtime"
      - dependency-name: "wasi-common"
      - dependency-name: "wasmtime-wasi"