# syntax=docker/dockerfile:1.4

ARG KIND_NODE_VERSION=v1.23.13
ARG RUNTIME=wasmtime
ARG GO_VERSION="1.21.1"

# modified from https://github.com/kubernetes-sigs/kind/blob/main/images/base/Dockerfile
# stage for building containerd
FROM golang:${GO_VERSION} as build-containerd
ARG CONTAINERD_VERSION="main"
ARG CONTAINERD_CLONE_URL="https://github.com/containerd/containerd"
# we don't build with optional snapshotters, we never select any of these
# they're not ideal inside kind anyhow, and we save some disk space
ARG BUILDTAGS="no_aufs no_zfs no_btrfs no_devmapper"
RUN git clone --filter=tree:0 "${CONTAINERD_CLONE_URL}" /containerd \
    && cd /containerd \
    && git checkout "${CONTAINERD_VERSION}" \ 
    && export CGO_ENABLED=1  \
    && make bin/ctr bin/containerd

FROM kindest/node:${KIND_NODE_VERSION}
COPY --from=build-containerd /containerd/bin/containerd /usr/local/bin/
COPY --from=build-containerd /containerd/bin/ctr /usr/local/bin/

RUN apt-get update -y && \
    apt-get install --no-install-recommends -y libdbus-1-3

ADD dist/bin/* /usr/local/bin/

ARG RUNTIME
RUN sed -i 's,SystemdCgroup = true,,' /etc/containerd/config.toml && \
    cat <<EOF >> /etc/containerd/config.toml
[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.wasm]
runtime_type = "io.containerd.${RUNTIME}.v1"
EOF