[package]
name = "containerd-shim-wasm-macros"
version.workspace = true
edition.workspace = true

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.32", features = ["full"]}
quote = "1.0.33"