# yaml-language-server: $schema=https://json.schemastore.org/github-action.json

name: Signing

on:
  workflow_call:
    inputs:
      runtime:
        required: true
        type: string
      os:
        required: true
        type: string
jobs:
  sign:
    name: Sign the binaries on ${{ inputs.os }}
    runs-on: ${{ inputs.os }}
    steps:
    - name: Setup cosign for signing
      uses: sigstore/cosign-installer@v3.6.0
      with:
        cosign-release: 'v2.2.2'
    - name: Sign the binaries
      run: |
        make dist-${{ inputs.runtime }}
        # Check if there's any files to archive as tar fails otherwise
        if stat dist/bin/* >/dev/null 2>&1; then
          echo "::notice::Signing the binary"
          cosign sign-blob --yes \
            --output-signature containerd-shim-${{ inputs.runtime }}-v1.sig \
            --output-certificate containerd-shim-${{ inputs.runtime }}-v1.pem \
            --bundle containerd-shim-${{ inputs.runtime }}-v1.bundle \
            dist/bin/containerd-shim-${{ inputs.runtime }}-v1
          
          cosign sign-blob --yes \
            --output-signature containerd-shim-${{ inputs.runtime }}d-v1.sig \
            --output-certificate containerd-shim-${{ inputs.runtime }}d-v1.pem \
            --bundle containerd-shim-${{ inputs.runtime }}d-v1.bundle \
            dist/bin/containerd-shim-${{ inputs.runtime }}d-v1

          cosign sign-blob --yes \
            --output-signature containerd-${{ inputs.runtime }}d.sig \
            --output-certificate containerd-${{ inputs.runtime }}d.pem \
            --bundle containerd-${{ inputs.runtime }}d.bundle \
            dist/bin/containerd-${{ inputs.runtime }}d
          
          # Copy the certs to the dist/bin folder
          cp *.sig dist/bin/
          cp *.pem dist/bin/
        else
          echo "::warning::No files to sign"
        fi